version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/api/Nhs.Appointments.Api"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/api/Nhs.Appointments.Core"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/api/Nhs.Appointments.Persistance"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/api/Nhs.Appointments.Api.Integration"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/api/Nhs.Appointments.Api.UnitTests"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/api/Nhs.Appointments.Core.UnitTests"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/src/api/Nhs.Appointments.Persistance.UnitTests"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"