version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/src/new-client"
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
