trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: environments
    type: object
    default: ["dev", "int", "stag", "pen", "perf", "prod"]

stages:
  - ${{ each env in parameters.environments }}:
      - template: "features/scripts/deploy-feature-toggles.yml"
        parameters:
          env: ${{env}}
          isValidBranch: ${{ or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/')) }}
