pool:
  vmImage: "ubuntu-latest"

parameters:
  - name: environments
    type: object
    default: ["dev", "pen", "perf"]
    values: ["dev", "pen", "perf"]
  - name: myaPipelineBuildId
    displayName: "The Build Id to be deployed"
    type: string

stages:
  - ${{ each env in parameters.environments }}:
      - template: scripts/pipeline-templates/deploy-artifact.yml
        parameters:
          myaPipelineBuildId: ${{ parameters.myaPipelineBuildId }}
          env: ${{env}}
          variable_group: nbs-mya-${{env}}
          httpFunctionAppName: nbs-mya-func-${{env}}-uks
          highLoadFunctionAppName: nbs-mya-hlfunc-${{env}}-uks
          serviceBusFunctionAppName: nbs-mya-sbfunc-${{env}}-uks
          timerFunctionAppName: nbs-mya-timerfunc-${{env}}-uks
          webServerName: nbs-mya-app-${{env}}-uks
          cosmosAccountName: nbs-mya-cdb-${{env}}-uks
          ${{ if eq(env, 'pen') }}:
            resourceGroup: nbs-mya-rg-${{env}}-uks
            serviceConnectionName: nhsuk-mya-nonprod
          ${{ elseif eq(env, 'perf') }}:
            resourceGroup: nbs-mya${{env}}-rg-stag-uks
            serviceConnectionName: nbs-mya${{env}}-rg-stag
          ${{ elseif eq(env, 'dev') }}:
            resourceGroup: nbs-mya${{env}}-rg-int-uks
            serviceConnectionName: nbs-mya${{env}}-rg-int
          ${{ else }}:
            resourceGroup: nbs-mya-rg-${{env}}-uks
            serviceConnectionName: nbs-mya-rg-${{env}}
          buildNumber: "$(Build.BuildNumber)"
          isHotfix: false
