trigger: none

pool:
  vmImage: "ubuntu-latest"

schedules:
  - cron: "0 2 * * *"
    displayName: "Capacity data extract schedule"
    branches:
      include:
      - main
    batch: false
    always: true

parameters:
  - name: env
    displayName: "Environment to import data into"
    type: string
    default: "prod"
    values: ["int", "stag", "prod"]
    
variables:
  - group: covid19bookingkv${{parameters.env}}uks
  - group: mya-booking-extract-${{parameters.env}}
  - name: cosmosAccountName 
    value: nbs-mya-cdb-${{parameters.env}}-uks
  - name: resourceGroupName
    value: nbs-mya-rg-${{parameters.env}}-uks

stages:
  - stage: "CreateDailyExtract"
    displayName: "Create Capicity data extract"
    jobs:
      - job: "GenerateCapacityDailyExtract"
        displayName: "Generate and send capacity extract"
        steps:
          - task: AzureCLI@2
            displayName: "Get Cosmos DB account connection string"
            inputs:
              azureSubscription: "nbs-mya-rg-${{parameters.env}}"
              scriptType: pscore
              scriptLocation: scriptPath
              scriptPath: "$(Build.SourcesDirectory)/scripts/cosmos-build/get_cosmos_connection_string.ps1"
              arguments: "-resourceGroup $(resourceGroupName) -cosmosAccountName $(cosmosAccountName)"
          - task: DotNetCoreCLI@2
            displayName: "Run tool to create capacity data extract"
            inputs:
              command: "run"
              projects: "data/CapacityDataExtracts/CapacityDataExtracts.csproj"
            env:
              COSMOS_ENDPOINT: $(COSMOS_ENDPOINT)
              COSMOS_TOKEN: $(COSMOS_TOKEN)
              MESH_MAILBOX_DESTINATION: $(toMeshMailboxId)
              MESH_WORKFLOW: $(meshWorkflowId)
              KeyVault__KeyVaultName: covid19bookingkv${{parameters.env}}uks
              KeyVault__TenantId: $(tenantId)
              KeyVault__ClientId: $(ClientId)
              KeyVault__ClientSecret: $(ClientSecret)
              MeshClientOptions__BaseUrl: $(meshApiBaseUri)
              MeshAuthorizationOptions__MailboxId: $(fromMeshMailboxId)
              MeshAuthorizationOptions__CertificateName: $(meshCertificateName)          
