trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: "Release"
  apiProjectPath: "src/api/Nhs.Appointments.Api/Nhs.Appointments.Api.csproj"
  apiUnitTestProjectPath: "tests/Nhs.Appointments.Api.UnitTests/Nhs.Appointments.Api.UnitTests.csproj"
  coreUnitTestProjectPath: "tests/Nhs.Appointments.Core.UnitTests/Nhs.Appointments.Core.UnitTests.csproj"
  persistanceUnitTestProjectPath: "tests/Nhs.Appointments.Persistance.UnitTests/Nhs.Appointments.Persistance.UnitTests.csproj"
  integrationTestProjectPath: "tests/Nhs.Appointments.Api.Integration/Nhs.Appointments.Api.Integration.csproj"
  cosmosDbSeederProjectPath: "mock-data/CosmosDbSeeder/CosmosDbSeeder.csproj"
  azure_devops_subscription_name: 'nbs-appts-rg-dev'
  azure_subscription_id: '07748954-52d6-46ce-95e6-2701bfc715b4'
  amsApiServerName: 'nbs-appts-func-dev-uks'
  amsWebServerName: 'nbs-appts-wa-dev-uks'
  resourceGroupName: 'nbs-appts-rg-dev-uks'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  PR_BUILD_ID: '$(Build.BuildNumber)'

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: "Build"
        steps:
          - task: DotNetCoreCLI@2
            displayName: dotnet Publish
            inputs:
              command: publish
              publishWebProjects: false
              projects: "$(apiProjectPath)"
              arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: false
              modifyOutputPath: false
          - task: DotNetCoreCLI@2
            displayName: "Run Api Unit Tests"
            inputs:
              command: "test"
              projects: "$(apiUnitTestProjectPath)"
          - task: DotNetCoreCLI@2
            displayName: "Run Core Unit Tests"
            inputs:
              command: "test"
              projects: "$(coreUnitTestProjectPath)"
          - task: DotNetCoreCLI@2
            displayName: "Run Persistance Unit Tests"
            inputs:
              command: "test"
              projects: "$(persistanceUnitTestProjectPath)"
          - task: ArchiveFiles@2
            displayName: Zip Api
            inputs:
              rootFolderOrFile: "$(Build.ArtifactStagingDirectory)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/out/appts-api-$(Build.BuildId).zip"
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: "Publish API Artifact"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/out"
              ArtifactName: "drop_api"
              publishLocation: "Container"
          - task: UseNode@1
            displayName: "Install Node"
            inputs:
              version: 20.x
          - script: |
              cd ./src/new-client
              npm ci 
              npm run lint
              npm run format:check
              npm run test:ci
            displayName: "Run Web App Tests"
          - task: PublishTestResults@2
            displayName: "Publish Web App Test Results"
            inputs:
              testResultsFiles: "junit.xml"
              testRunTitle: NBS Appointments Management Service Client Tests
              testResultsFormat: "JUnit"
              publishRunAttachments: true
              searchFolder: '$(Build.SourcesDirectory)/src/new-client'
            condition: succeededOrFailed()
          - script: |
              cd ./src/new-client
              npm run build
              mv .next/static .next/standalone/.next/static
            displayName: "Build Web App"
          - task: ArchiveFiles@2
            displayName: Zip Web Client
            inputs:
              rootFolderOrFile: "$(Build.SourcesDirectory)/src/new-client/.next"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/web/next.zip"
          - task: PublishBuildArtifacts@1
            displayName: "Publish Web App"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/web"
              ArtifactName: "drop_web"
              publishLocation: "Container"
          - task: PublishBuildArtifacts@1
            displayName: "Publish Terraform"
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/infrastructure"
              ArtifactName: "drop_terraform"
              publishLocation: "Container"


      - job: "RunIntegrationAndE2ETests"
        displayName: Run integration and E2E tests
        steps:
          - task: AzureCLI@2
            displayName: 'Create cosmos account'
            inputs:
              azureSubscription: $(azure_devops_subscription_name)
              scriptType: pscore
              scriptLocation: scriptPath
              scriptPath: "$(Build.SourcesDirectory)/scripts/cosmos-pr-build/create_cosmos_db.ps1"
          - task: AzureCLI@2
            displayName: 'Get cosmos account connection string'
            inputs:
              azureSubscription: $(azure_devops_subscription_name)
              scriptType: pscore
              scriptLocation: scriptPath
              scriptPath: "$(Build.SourcesDirectory)/scripts/cosmos-pr-build/get_cosmos_connection_string.ps1"
          - script: printenv
            displayName: "Print env var"
          - script: |
              docker compose up --build --detach
            displayName: "Start docker containers" 
          - task: DotNetCoreCLI@2
            displayName: "Run Integration Tests"
            inputs:
              command: "test"
              projects: "$(integrationTestProjectPath)"
              arguments: '--logger:"trx;logfilename=apptsServiceTests.trx"'
          - task: PublishTestResults@2
            displayName: 'Publish Integration Test Results'
            inputs:
              testResultsFiles: 'apptsServiceTests.trx'
              testRunTitle: NBS Appointments Management Service Integration Tests
              testResultsFormat: 'VSTest'
              publishRunAttachments: true
              searchFolder: '$(System.DefaultWorkingDirectory)\tests\Nhs.Appointments.Api.Integration\TestResults'
            condition: succeededOrFailed()
          - task: DotNetCoreCLI@2
            displayName: "Run Integration Tests"
            inputs:
              command: "test"
              projects: "$(integrationTestProjectPath)"
              arguments: '--logger:"trx;logfilename=apptsServiceTests.trx"'
          - task: DotNetCoreCLI@2
            displayName: "Reset and seed cosmos containers"
            inputs:
              command: "run"
              projects: "$(cosmosDbSeederProjectPath)"
          - task: UseNode@1
            displayName: "Install Node"
            inputs:
              version: 20.x
          - script: |
              cd /src/new-client
              npm ci
              npm run test:e2e
            displayName: "Run E2E tests"
          - task: AzureCLI@2
            displayName: 'Delete cosmos account'
            inputs:
              azureSubscription: $(azure_devops_subscription_name)
              scriptType: pscore
              scriptLocation: scriptPath
              scriptPath: "$(Build.SourcesDirectory)/scripts/cosmos-pr-build/delete_cosmos_db.ps1"
              condition: always()
          
              
  - stage: DeployDev
    condition: and(succeeded(), eq(variables.isMain, true))
    variables:
      - group: 'nbs-ams-dev'
    displayName: Deploy Dev
    jobs:
      - job: RunTerraformPlan
        displayName: Run Terraform Plan
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@0
            displayName: Download Terraform Artifact
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop_terraform'
              downloadPath: '$(Pipeline.Workspace)'
          - task: AzureCLI@2
            displayName: 'Run Terraform Plan'
            inputs:
              scriptType: pscore
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              azureSubscription: $(azure_devops_subscription_name)
              inlineScript: |
                $env:ARM_CLIENT_ID=$env:servicePrincipalId
                $env:ARM_CLIENT_SECRET=$env:servicePrincipalKey
                $env:ARM_TENANT_ID=$env:tenantId
                $env:ARM_SUBSCRIPTION_ID="$(azure_subscription_id)"
                cd $(Pipeline.Workspace)\drop_terraform\environments\dev
                terraform init
                terraform plan -no-color -input=false -var="HMAC_SIGNING_KEY=$(HMAC_SIGNING_KEY)" -var="API_KEYS=$(API_KEYS)" -var="APIM_SUBSCRIPTION_KEY=$(APIM_SUBSCRIPTION_KEY)"
      - job: "ApproveTerraformPlan"
        dependsOn: RunTerraformPlan
        displayName: Approve Terraform Plan
        pool: server
        steps:
          - task: ManualValidation@0
            displayName: 'Review Terraform Plan'
            inputs:
              notifyUsers: ''
              instructions: Review plan and approve
      - deployment: ApplyTerraform
        dependsOn: ApproveTerraformPlan
        displayName: "Apply Terraform"
        environment: nbs-appts-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - task: DownloadBuildArtifacts@0
                  displayName: Download Terraform Artifact
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop_terraform'
                    downloadPath: '$(Pipeline.Workspace)'
                - task: AzureCLI@2
                  displayName: 'Apply Terraform'
                  name: ApplyTerraformTask
                  inputs:
                    scriptType: pscore
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    azureSubscription: $(azure_devops_subscription_name)
                    inlineScript: |
                      $env:ARM_CLIENT_ID=$env:servicePrincipalId
                      $env:ARM_CLIENT_SECRET=$env:servicePrincipalKey
                      $env:ARM_TENANT_ID=$env:tenantId
                      $env:ARM_SUBSCRIPTION_ID="$(azure_subscription_id)"
                      cd $(Pipeline.Workspace)\drop_terraform\environments\dev
                      terraform init
                      terraform apply -no-color -input=false -auto-approve -var="HMAC_SIGNING_KEY=$(HMAC_SIGNING_KEY)" -var="API_KEYS=$(API_KEYS)" -var="APIM_SUBSCRIPTION_KEY=$(APIM_SUBSCRIPTION_KEY)"
      - job: "DeployWeb"
        dependsOn: ApplyTerraform
        displayName: "Deploy webapp to Dev"
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@0
            displayName: "Download Web App Artifact"
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop_web'
              downloadPath: '$(Pipeline.Workspace)'
          - task: AzureWebApp@1
            displayName: "Deploy Web App"
            inputs:
              azureSubscription: $(azure_devops_subscription_name)
              appType: 'webAppLinux'
              appName: $(amsWebServerName)
              package: '$(Pipeline.Workspace)/drop_web/next.zip'
              deploymentMethod: 'auto'
              startUpCommand: 'node standalone/server.js'
      - job: "DeployApi"
        dependsOn: ApplyTerraform
        displayName: Deploy Api
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@0
            displayName: Download Api Artifact
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop_api'
              downloadPath: '$(Pipeline.Workspace)'
          - task: AzureFunctionApp@2
            displayName: Deploy Api
            inputs:
              connectedServiceNameARM: $(azure_devops_subscription_name)
              appType: 'functionApp'
              appName: '$(amsApiServerName)'
              package: '$(Pipeline.Workspace)/**/*.zip'
              deploymentMethod: 'auto'