# this pipeline should be restricted so that it can't be run manually
trigger:
  branches:
    include:
      - main
      - release/*
      - hotfix/*

pool:
  vmImage: "ubuntu-latest"

variables:
  prBuildServiceConnectionName: "nbs-myacicd-rg-int"
  prDockerServiceConnectionName: "nbs-mya-container-registry-sc"

stages:
  - stage: SetBuildNumber
    displayName: "Set Build Number"
    jobs:
      - job: SetBuildNumberJob
        steps:
          - powershell: |
              .\scripts\extract-version.ps1 -branchName "$(Build.SourceBranch)" -buildNumber "$(Build.BuildNumber)"
            name: ExtractVersionStep
            displayName: "Extract version from branch name"

  - template: scripts/pipeline-templates/build.yml
    parameters:
      prBuildServiceConnectionName: $(prBuildServiceConnectionName)
      prDockerServiceConnectionName: $(prDockerServiceConnectionName)
