trigger:
  branches:
    include:
      - hotfix/*

pool:
  vmImage: "ubuntu-latest"

variables:
  prBuildServiceConnectionName: "nbs-myacicd-rg-int"
  prDockerServiceConnectionName: "nbs-mya-container-registry-sc"

parameters:
  - name: environments
    type: object
    default: ["stag", "prod"]
    values: ["stag", "prod"]

stages:
  - template: scripts/pipeline-templates/build.yml
    parameters:
      prBuildServiceConnectionName: $(prBuildServiceConnectionName)
      prDockerServiceConnectionName: $(prDockerServiceConnectionName)

  - ${{ each env in parameters.environments }}:
      - template: scripts/pipeline-templates/deploy.yml
        parameters:
          env: ${{env}}
          variable_group: nbs-mya-${{env}}
          httpFunctionAppName: nbs-mya-func-${{env}}-uks
          highLoadFunctionAppName: nbs-mya-hlfunc-${{env}}-uks
          serviceBusFunctionAppName: nbs-mya-sbfunc-${{env}}-uks
          timerFunctionAppName: nbs-mya-timerfunc-${{env}}-uks
          webServerName: nbs-mya-app-${{env}}-uks
          cosmosAccountName: nbs-mya-cdb-${{env}}-uks
          resourceGroup: nbs-mya-rg-${{env}}-uks
          serviceConnectionName: nbs-mya-rg-${{env}}
          isHotfix: true
