trigger: none

pool:
  vmImage: "ubuntu-latest"

schedules:
  - cron: "0 2 * * *"
    displayName: "Booking data extract schedule"
    branches:
      include:
      - APPT-352/*
    batch: false
    always: true

stages:
  - stage: "CreateDailyExtract"
    displayName: "Create booking data extract"
    jobs:
      - job: "GenerateBookingDailyExtract"
        displayName: "Generate and send booking extract"
        steps:
          - task: DotNetCoreCLI@2
            displayName: "Run tool to create booking data extract"
            inputs:
              command: "run"
              projects: "data/BookingsDataExtract/BookingsDataExtract.csproj"
