receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  splunk_hec/logs:
    token: "e2c421cf-9228-4ab2-a6e8-877741df569a"
    endpoint: "http://splunk:8088/services/collector"
    index: "mya-logs"
    disable_compression: false
    timeout: 10s
    tls:
      insecure_skip_verify: true
  splunk_hec/traces:
    token: "e2c421cf-9228-4ab2-a6e8-877741df569a"
    endpoint: "http://splunk:8088/services/collector"
    index: "mya-traces"
    disable_compression: false
    timeout: 10s
    tls:
      insecure_skip_verify: true
  splunk_hec/metrics:
    token: "e2c421cf-9228-4ab2-a6e8-877741df569a"
    endpoint: "http://splunk:8088/services/collector"
    index: "mya-metrics"
    disable_compression: false
    timeout: 10s
    tls:
      insecure_skip_verify: true
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

processors:
  batch:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [splunk_hec/logs, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [splunk_hec/traces, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [splunk_hec/metrics, debug]
