parameters:
  - name: prBuildServiceConnectionName
    type: string
  - name: prDockerServiceConnectionName
    type: string

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: "Build"
        variables:
          apiProjectPath: "src/api/Nhs.Appointments.Api/Nhs.Appointments.Api.csproj"
          apiUnitTestProjectPath: "tests/Nhs.Appointments.Api.UnitTests/Nhs.Appointments.Api.UnitTests.csproj"
          coreUnitTestProjectPath: "tests/Nhs.Appointments.Core.UnitTests/Nhs.Appointments.Core.UnitTests.csproj"
          persistanceUnitTestProjectPath: "tests/Nhs.Appointments.Persistance.UnitTests/Nhs.Appointments.Persistance.UnitTests.csproj"
          bookingExtractsTestProjectPath: "tests/BookingDataExtracts.UnitTests/BookingDataExtracts.UnitTests.csproj"
          capacityExtractsTestProjectPath: "tests/CapacityDataExtracts.UnitTests/CapacityDataExtracts.UnitTests.csproj"
          cosmosDbSeederTestProjectPath: "tests/CosmosDbSeederTests/CosmosDbSeederTests.csproj"
          bookingExtractDockerFilePath: "BookingDataExtractDockerfile"
          capacityExtractDockerFilePath: "CapacityDataExtractDockerfile"
        steps:
          - task: PowerShell@2
            displayName: "Run script tests"
            inputs:
              targetType: "inline"
              script: |
                Set-Location ./scripts
                Invoke-Pester
              pwsh: true
          - task: PowerShell@2
            displayName: "Extract MYA version"
            name: ExtractVersionStep
            inputs:
              targetType: "inline"
              script: |
                .\scripts\extract-version.ps1 -branchName "$(Build.SourceBranch)" -buildNumber "$(Build.BuildNumber)"
              pwsh: true
          - task: PowerShell@2
            displayName: "Write MYA version to file"
            inputs:
              targetType: "inline"
              script: |
                Set-Content -Path $(Pipeline.Workspace)/version_number.txt -Value "$(ExtractVersionStep.ExtractedBuildNumber)"
              pwsh: true
          - task: PublishBuildArtifacts@1
            displayName: "Publish MYA version to artifact"
            inputs:
              PathtoPublish: "$(Pipeline.Workspace)/version_number.txt"
              ArtifactName: "drop_version_number"
              publishLocation: "Container"
          - task: SonarCloudPrepare@3
            displayName: "Prepare analysis on SonarCloud"
            inputs:
              SonarCloud: "nhsdigital-sonarcloud"
              organization: "nhsdigital"
              scannerMode: "dotnet"
              projectKey: "NHSDigital_nbs-appointments-management-service"
              projectName: "nbs-appointments-management-service"
              extraProperties: |
                sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
                sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/**/coverage.opencover.xml
                sonar.scanner.scanAll=false
                sonar.coverage.exclusions=**/FunctionConfigurationExtensions.cs,**/ServiceRegistration.cs,**/ConsoleLogNotifications.cs,**/Program.cs,**/Nhs.Appointments.Persistance/**
          - task: DotNetCoreCLI@2
            displayName: "dotnet Publish"
            inputs:
              command: publish
              publishWebProjects: false
              projects: $(apiProjectPath)
              arguments: "--output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: false
              modifyOutputPath: false
          - task: DotNetCoreCLI@2
            displayName: "Run Api Unit Tests"
            inputs:
              command: "test"
              projects: $(apiUnitTestProjectPath)
              arguments: '--collect "XPlat Code Coverage;Format=opencover"'
          - task: DotNetCoreCLI@2
            displayName: "Run Core Unit Tests"
            inputs:
              command: "test"
              projects: $(coreUnitTestProjectPath)
              arguments: '--collect "XPlat Code Coverage;Format=opencover"'
          - task: DotNetCoreCLI@2
            displayName: "Run Persistance Unit Tests"
            inputs:
              command: "test"
              projects: $(persistanceUnitTestProjectPath)
              arguments: '--collect "XPlat Code Coverage;Format=opencover"'
          - task: DotNetCoreCLI@2
            displayName: "Run Booking Extracts unit tests"
            inputs:
              command: "test"
              projects: $(bookingExtractsTestProjectPath)
              arguments: '--collect "XPlat Code Coverage;Format=opencover"'
          - task: DotNetCoreCLI@2
            displayName: "Run Capacity Extracts unit tests"
            inputs:
              command: "test"
              projects: $(capacityExtractsTestProjectPath)
              arguments: '--collect "XPlat Code Coverage;Format=opencover"'
          - task: DotNetCoreCLI@2
            displayName: "Run Cosmos Db Seeder tests"
            inputs:
              command: "test"
              projects: $(cosmosDbSeederTestProjectPath)
              arguments: '--collect "XPlat Code Coverage;Format=opencover"'
          - task: SonarCloudAnalyze@3
            displayName: "Run Code Analysis"
          - task: SonarCloudPublish@3
            displayName: "Publish Sonar cloud results"
            inputs:
              pollingTimeoutSec: "300"
          - task: ArchiveFiles@2
            displayName: Zip Api
            inputs:
              rootFolderOrFile: $(Build.ArtifactStagingDirectory)
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/out/mya-api-$(Build.BuildId).zip"
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: "Publish API Artifact"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/out"
              ArtifactName: "drop_api"
              publishLocation: "Container"
          - task: UseNode@1
            displayName: "Install Node"
            inputs:
              version: 20.x
          - script: |
              cd ./src/client
              npm ci 
              npm run lint
              npm run format:check
              npm run test:ci
            displayName: "Run Web App Tests"
          - script: |
              cd ./src/client
              npm run tsc
            displayName: "Check TypeScript Syntax"
            continueOnError: false
          - script: |
              cd ./src/client
              npm run lint
            displayName: "Run ESLint"
            continueOnError: false
          - task: PublishTestResults@2
            displayName: "Publish Web App Test Results"
            inputs:
              testResultsFiles: "junit.xml"
              testRunTitle: NBS Appointments Management Service Client Tests
              testResultsFormat: "JUnit"
              publishRunAttachments: true
              searchFolder: "$(Build.SourcesDirectory)/src/client"
            condition: succeededOrFailed()
          - script: |
              cd ./src/client
              npm run build
              mv .next/static .next/standalone/.next/static
            displayName: "Build Web App"
            env:
              BUILD_NUMBER: "$(ExtractVersionStep.extractedBuildNumber)"
          - task: ArchiveFiles@2
            displayName: Zip Web Client
            inputs:
              rootFolderOrFile: "$(Build.SourcesDirectory)/src/client/.next"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/web/next.zip"
          - task: PublishBuildArtifacts@1
            displayName: "Publish Web App"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/web"
              ArtifactName: "drop_web"
              publishLocation: "Container"
          - task: Docker@2
            displayName: Build and push booking extract image to container registry
            inputs:
              command: buildAndPush
              repository: booking-extract
              dockerfile: $(bookingExtractDockerFilePath)
              containerRegistry: ${{parameters.prDockerServiceConnectionName}}
              tags: |
                $(ExtractVersionStep.extractedBuildNumber)
          - task: Docker@2
            displayName: Build and push capacity extract image to container registry
            inputs:
              command: buildAndPush
              repository: capacity-extract
              dockerfile: $(capacityExtractDockerFilePath)
              containerRegistry: ${{parameters.prDockerServiceConnectionName}}
              tags: |
                $(ExtractVersionStep.extractedBuildNumber)
          - task: PublishBuildArtifacts@1
            displayName: "Publish Terraform"
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/infrastructure"
              ArtifactName: "drop_terraform"
              publishLocation: "Container"
          - task: PublishBuildArtifacts@1
            displayName: "Publish Scripts"
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/scripts"
              ArtifactName: "drop_scripts"
              publishLocation: "Container"