parameters:
  - name: env
    type: string
  - name: isValidBranch
    type: boolean

stages:
  - stage: DeployFeatures${{parameters.env}}
    displayName: Deploy Features ${{parameters.env}}
    condition: and(succeeded(), eq(${{parameters.isValidBranch}}, true))
    dependsOn: []
    jobs:
      - deployment: ApplyFeatureToggles
        displayName: "Apply Feature Toggles"
        environment: nbs-mya-${{parameters.env}}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  displayName: "Apply Feature Toggles"
                  inputs:
                    ${{ if ne(parameters.env, 'perf') }}:
                      azureSubscription: "nbs-mya-rg-${{parameters.env}}"
                    ${{ if eq(parameters.env, 'perf') }}:
                      azureSubscription: "nbs-mya${{parameters.env}}-rg-stag"
                    scriptType: pscore
                    scriptLocation: scriptPath
                    scriptPath: "$(Build.SourcesDirectory)/features/scripts/import-flags.ps1"
                    arguments: >
                      -appConfigName nbs-mya-config-${{parameters.env}}-uks 
                      -sourceFile $(Build.SourcesDirectory)/features/${{parameters.env}}.feature.flags.json
